---
- name: Download connector J
  get_url:
    url: "{{mysql_connectorj_mirror}}/{{ mysql_connectorj_redis_filename }}"
    dest: "{{ glassfish_download_dir }}/{{ mysql_connectorj_redis_filename }}"
    mode: 'u=rw,go=r'
- name: install Connector J
  become: yes
  unarchive:
    src: "{{ glassfish_download_dir }}/{{ mysql_connectorj_redis_filename }}"
    dest: "/opt"
    copy: false
    owner: root
    group: root
    mode: 'go-w'
- name: Copy connector to Glassfish
  become: yes
  command: mv /opt/{{mysql_connectorj_redis}}-{{ mysql_connectorj_version }}/{{mysql_connectorj_redis}}-{{ mysql_connectorj_version }}-bin.jar {{ glassfish_install_dir }}/{{ glassfish_product }}/glassfish/domains/domain1/lib
- name: Removing downloaded connector file
  file: path="{{ glassfish_download_dir }}/{{ mysql_connectorj_redis_filename }}"
   state=absent
- name: Removing unzipped connector folder from opt
  file: path="/opt/{{mysql_connectorj_redis}}-{{ mysql_connectorj_version }}"
   state=absent