---
- hosts: localhost
  become: true
  pre_tasks:
   - name: Update cache if is needed
     apt: update_cache=yes cache_valid_time=3600
  roles:
  - geerlingguy.nfs
  - angstwad.docker_ubuntu
  - ansible-role-tiw-user
  - mrlesmithjr.oracle-java8
  - ansible-role-sts
  - gantsign.maven
  - geerlingguy.mysql
  - ansible-role-glassfish
  - ansible-role-jboss-forge
  tasks:
  - apt: name={{ item }} state=present
    with_items:
        - wget
        - curl
        - vim
        - git
        - mysql-workbench
        - chromium-browser
  - file:
     path=/opt
     owner=tiw
     group=tiw
     recurse=yes    
